### ISSUE TITLE
Is it possible to apply this plugin to "stepFunctions"

### ISSUE THREAD

**Issue by J-Whitfield** [anantab/serverless-plugin-ifelse#13]
serverlessIfElse:
    - If: '"${self:custom.stage}" == "dev"'
      ElseExclude:
        -  provider.role
        - stepFunctions.func1

When trying to execute this , the plugin is not outputting that it is excluding the stepFunctions, however it will output it is excluding provider.role

**Comment by anantab** [comment]
Hi @J-Whitfield, Serverless does not parse stepFunctions config from the serverless.yml file, hence this plugin does not see  stepFunctions config variables. So it is not possible to apply if else rule to it.
