### ISSUE TITLE
Would this plugin work alongside serverless-offline?

### ISSUE THREAD

**Issue by diegoaguilar** [anantab/serverless-plugin-ifelse#6]
I got the following `serverlessIfElse` definition:

```
  serverlessIfElse:
    - ExcludeIf: 
        functions.post.environment.RENDERED_CONTENTFUL_ENTRY_TOPIC_ARN: '"${self:provider.stage}" == "development"'
```

I made sure that `provider.stage is set to development` is set to `'development'`.

However, when running server, I can notice:

* There's any serverless-plugin-ifelse log when running `serverless offline` setting `SLS_DEBUG=*` before
* The value set at `post.environment.RENDERED_CONTENTFUL_ENTRY_TOPIC_ARN` gets assigned.

In a few words, this plugin has no effect when serverless online is running. I made a test with `serverless deploy` and I could see it having effect.

Any opinions?

**Comment by anantab** [comment]
Please make sure you include ``` serverless-plugin-ifelse``` before ```serverless-offline``` plugin under plugins.
```
plugins:
  - serverless-plugin-ifelse
  - serverless-offline
```
